# Inspiré de config_solo12.yaml

robot:
    interface: enp6s0f1  #enp3s0(?)
    joint_modules:
        motor_numbers: [0, 3, 2, 1, 5, 4]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 12.                       #MODIF avec bolt_driver.yaml
        reverse_polarities: [
            true, true, true, true, false, false     #MODIF avec bolt_driver.yaml
        ]
        lower_joint_limits: [
            -0.9, -1.7, -3.4, -0.9, -1.7, -3.4   #MODIF avec test sur systeme
        ]
        upper_joint_limits: [
            0.9, 1.7, +3.4, +0.9, +1.7, +3.4    #MODIF avec test sur systeme
        ]
        max_joint_velocities: 80.
        safety_damping: 0.3                         #MODIF avec bolt_driver.yaml
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
      #AUTO, AUTO, AUTO, AUTO, AUTO, AUTO
      #POS, NEG, POS, NEG, NEG, POS             #MODIF avec bolt_driver.yaml
      POS, POS, POS, POS, POS, POS               
    ]
    position_offsets: [ # [ FLHAA, FLHFE, FLKFE, FRHAA, FRHFE, FRKFE ]
            # 0.39620453147888185, 0.42925912553999157, 0.2865775082455741, 0.4388355898751153, 0.16206956309212578, 0.4076508879396651
              0.2403, 0.3996, 0.2668, 0.5836, 0.1053, 0.4465
              #0,0,0,0,0,0
            #-0.149, -0.030, -0.019, 0.144, -0.048, +0.038
    ]                                             #Calibration cpp codes made
    Kp: 3.
    Kd: 0.05
    T: 2.                                         #MODIF avec bolt_driver.yaml
    dt: 0.001