publisher_forward_position_controller:
  ros__parameters:

    controller_name: "forward_position_controller"
    wait_sec_between_publish: 0.25

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.0, 0.0, -1.3, 0.3, 1, -0.4]
    pos2: [0.0, 0.0, 0.3, -1.3, -0.4, 1]
    pos3: [0.0, 0.0, 1.3, -0.3, -1, 0.4]
    pos4: [0.0, 0.0, -0.3, 1.3, 0.4, -1]

    #pos1: [0.85, -0.85, 0.0, 0.0, 0.0, 0.0]
    #pos2: [1.7, -1.7, 0.0, 0.0, 0.0, 0.0]
    #pos3: [0.85, -0.85, 0.0, 0.0, 0.0, 0.0]
    #pos4: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    joints:
      - FL_HAA
      - FR_HAA
      - FL_HFE
      - FR_HFE
      - FL_KFE
      - FR_KFE

    check_starting_point: false
    starting_point_limits:
      FL_HAA: [-0.01,0.01]
      FR_HAA: [-0.01,0.01]
      FL_HFE: [-0.01,0.01]
      FR_HFE: [-0.01,0.01]
      FL_KFE: [-0.01,0.01]
      FR_KFE: [-0.01,0.01]
