controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    forward_command_controller:
      type: forward_command_controller/ForwardCommandController

    position_velocity_effort_gain_controller:
      type: position_velocity_effort_gain_controller/PosVelTorGainsController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


position_velocity_effort_gain_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_KFE
      - FL_HFE
      - FR_KFE
      - FR_HFE
    origin: [0.0, 0.0, 1.0]

    interface_name: gain_kp

forward_command_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_KFE
      - FL_HFE
      - FR_KFE
      - FR_HFE
    origin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    interface_name: position
